---
  vars:
     testvar: 
        aaa:
           filename: aaa.txt
        bbb:
           filename: bbb.txt
  
  tasks:
     
    - include_tasks: show-testvar.yml
      vars:
              testvar_id: "{{item.key}}"
              testvar_file: "{{item.value.filename}}"
      with_dict: "{{ testvar }}"