  - name:  Set Expected Location of Agent Control Utility
    set_fact:       
       emctl_path: /u01/app/oracle/oem13c_agent/agent_inst/bin/emctl
  
  - name: Check if Cloud Control Agent Installed
    stat: 
       path: "{{ emctl_path }}"
    register: agent_emctl

  - name: Create List of Grid Blackout Targets
    set_fact: 
       grid_targets: [] 
    when: agent_emctl.stat.exists and grid_shutdown_needed  

  - name: Get Name of Grid Blackout Targets
    shell: |
         {{ emctl_path }} config agent listtargets | egrep -i -e "( has\]$| osm_instance\]$| oracle_listener\]$)" | sed 's/^\[//' | sed 's/\]$//' | sed 's/, /,/' | awk -F, '{printf("%s:%s\n",$1,$2)}'
    register: grid_blackout_target_list
    changed_when: false
    when: agent_emctl.stat.exists and grid_shutdown_needed

  - name: Populate List of Grid Blackout Targets 
    set_fact:
            grid_targets: "{{ grid_targets + [item] }}"
    with_items: "{{ grid_blackout_target_list.stdout_lines }}"
    when: agent_emctl.stat.exists and grid_shutdown_needed

  - name: Create List of Database Blackout Targets 
    set_fact: 
       database_targets: [] 
    when: agent_emctl.stat.exists and database_shutdown_needed 

  - name: Get List of Database Targets
    shell: |
          {{ emctl_path }} config agent listtargets | egrep -i -e " oracle_database\]$" | sed 's/^\[//' | sed 's/\]$//' | sed 's/, /,/' | awk -F, '{printf("%s:%s\n",$1,$2)}'
    register: database_blackout_target_list
    changed_when: false
    when: agent_emctl.stat.exists and database_shutdown_needed

  - name: Populate List of Database Blackout Targets 
    set_fact:
            database_targets: "{{ database_targets + [item] }}"
    with_items: "{{ database_blackout_target_list.stdout_lines }}"
    when: agent_emctl.stat.exists and database_shutdown_needed

  - name: Start Grid Blackout
    shell: |
           {{ emctl_path}} start blackout Grid_Patching {{ grid_targets | join(' ') }}
    when: agent_emctl.stat.exists and grid_shutdown_needed and blackout_action == "start" 

  - name: Start Database Blackout
    shell: |
           {{ emctl_path}} start blackout Database_Patching {{ database_targets | join(' ') }}
    when: agent_emctl.stat.exists and database_shutdown_needed and blackout_action == "start" 

  - name: Stop Grid Blackout
    shell: |
           {{ emctl_path}} stop blackout Grid_Patching 
    when: agent_emctl.stat.exists and grid_shutdown_needed and blackout_action == "stop" 

  - name: Stop Database Blackout
    shell: |
           {{ emctl_path}} stop blackout Database_Patching 
    when: agent_emctl.stat.exists and database_shutdown_needed and blackout_action == "stop" 



