---

- name: Restart all databases in the current Oracle Home
  shell: "export ORACLE_HOME={{ oracle_database_oracle_home }}; {{ oracle_database_oracle_home }}/bin/srvctl start home -o {{ oracle_database_oracle_home }} -s {{ oracle_statefile }}"

- name: Remove state file
  file:
     path: "{{ oracle_statefile }}"
     state: absent

- name: Get database type
  set_fact:
    database_type: "{{ target_hosts.split(',')[0] | regex_replace('(^.*)_.*$','\\1') }}"

- name: Set FSFO Mode
  include_role:
     name: hmpps-delius-oracledb-ha
     tasks_from: set-fsfo-mode.yml
  vars:
     delegation_host: "{{ hostvars[groups[database_type + '_primarydb'][0]]['inventory_hostname'] }}"
     standby1: "{{ database_type + '_standbydb1' }}"
     standby2: "{{ database_type + '_standbydb2' }}"
     high_availability_count: "{{ database[database_type]['high_availability_count'] }}"