---

# Only Run Post Install Datapatch or SQL Script on Primary databases

- name: Run Datapatch
  shell:  |
          . ~/.bash_profile
          cd {{ oracle_database_oracle_home }}/OPatch
          ./datapatch
  when: database_primary_sid is defined
