---
   - name: Define Oracle State File for Shutting Down Databases
     set_fact:
         oracle_statefile: "{{ oracle_database_oracle_home }}/dbs/patching_statefile"

   - name: Remove Previous Statefile
     file:
        path: "{{ oracle_statefile }}"
        state: absent
     when: database_shutdown_needed|bool

   - name: Shutdown all running databases in the current Oracle Home
     shell: "export ORACLE_HOME={{ oracle_database_oracle_home }}; {{ oracle_database_oracle_home }}/bin/srvctl stop home -o {{ oracle_database_oracle_home }} -s {{ oracle_statefile }} -t IMMEDIATE"

