---

- name: Check if patch {{ patch_number }} is installed on Grid Infrastructure
  shell: |
         grep -Ec "<patchID>{{ patch_number }}</patchID>" /tmp/grid_opatch_out.xml || [[ $? == 1 ]]
  register: grid_patch_present
  changed_when: false 
  when: grid_patch | bool

- name: Set Patch Required on Grid
  set_fact:
     required_patches: "{{ required_patches|combine({patch_id: {'already_applied_to_grid': grid_patch_present.stdout | bool}}, recursive=true) }}"
  when: (grid_patch | bool) 

- name: Check if patch {{ patch_number }} is installed on Database 
  shell: |
         grep -Ec "<patchID>{{ patch_number }}</patchID>" /tmp/database_opatch_out.xml || [[ $? == 1 ]]
  register: database_patch_present
  changed_when: false
  when: database_patch | bool

- name: Set Patch Required on Database
  set_fact:
     required_patches: "{{ required_patches|combine({patch_id: {'already_applied_to_database': database_patch_present.stdout | bool}}, recursive=true) }}"
  when: (database_patch | bool)